apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":null,"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app":"clickhouse-operator","clickhouse.altinity.com/chop":"0.23.5"},"name":"etc-clickhouse-operator-confd-files","namespace":"test"}}
  creationTimestamp: "2024-06-13T10:51:57Z"
  labels:
    app: clickhouse-operator
    clickhouse.altinity.com/chop: 0.23.5
  name: etc-clickhouse-operator-confd-files
  namespace: test
  resourceVersion: "304"
  uid: 9531487c-0ca1-4541-897f-7a74dca4a283
